# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 417fab9bca4f4e5776b3777ecf7703ef41c3cc7343fa2313f63ea7e140ef1db9f86b3ef2464ff74741ec7dad22985ccc725be1a26e317682fc9b1fa1f9eaba76

test:
  secret_key_base: 673fa2aae16283ddd0c4d92ebf132d480f231530b90a76d374f7733acae5ebc4d34afebfb0bbbfc80050cc3ab8a5335f94673e2bdb69a61099cb3c46e51328fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
